[versions]

# Gradle Plugins
androidGradlePlugin = "8.7.2"
kotlinGradlePlugin = "2.0.21"
kspGradlePlugin = "2.0.21-1.0.27"

# Kotlin
kotlinCompiler = "1.5.15"

# Compose
composeBom = "2024.11.00"
composeActivity = "1.9.3"

# AndroidX
androidCore = "1.15.0"
androidLifecycle = "2.8.7"

# Koin
koin = "4.0.0"

# Retrofit
retrofit = "2.11.0"

# OkHttp
okhttp3 = "4.12.0"

# Moshi
moshi = "1.15.1"


[libraries]

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-material = { group = "androidx.compose.material3", name = "material3" }

# AndroidX
android-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidCore" }
android-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidLifecycle" }

# Koin
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-android-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }

# Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }

# OkHttp
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }

# Moshi
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }


[plugins]

# Android
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }

# Kotlin
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinGradlePlugin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinGradlePlugin" }

# KSP
ksp = { id = "com.google.devtools.ksp", version.ref = "kspGradlePlugin" }