name: Build and Release APK

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: "Release version (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"

env:
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.tagname }}
  cancel-in-progress: true

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.tagname }}
          git push origin ${{ github.event.inputs.tagname }}

  publish-github-release:
    name: "Publish GitHub Release"
    runs-on: ubuntu-latest

    needs: create-release-tag

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout keystore repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.KEY_STORE_GIT_REPOSITORY }}
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: app-android/keystore

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: "Release ${{ github.event.inputs.tagname }}"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tagname }}
          draft: true
          file: app-android/build/outputs/apk/release/app-android-release.apk
          asset_name: PixivCompose-${{ github.event.inputs.tagname }}.apk